name: material_tag_editor
description: A simple tag editor for inputing tags. This is design to act and feel similar the standard Material TextField as much as possible.
version: 1.0.0
homepage: https://github.com/panuavakul/material_tag_editor.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
